name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        env: 
          SLACK_WEB_HOOK: ${{secrets.SLACK_WEB_HOOK}}
        run: |
          echo ${SLACK_WEB_HOOK}
          echo ${{SLACK_WEB_HOOK}}
          touch .env
          echo "SLACK_WEB_HOOK=${{secrets.SLACK_WEB_HOOK}}" >> .env
          echo ${{secrets.SLACK_WEB_HOOK}}
          echo ${process.env.SLACK_WEB_HOOK}
          sh ./kusowifi.sh
