name: wifi notification work

on: 
  push:
    schedule:
      - cron: '*/5 * * * *'

jobs:
  my-job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          TEAM: ${{secrets.TEAM}}
          BSTART: ${{secrets.BSTART}}
          TOKEN: ${{secrets.SLACK_TOKEN}}
          TOKEN_GENE: "nUF9Jp7JrWK30VvL0z6SggPy"
        run: sh ./kusowifi.sh
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/T02633YV1GW/B02R6HYP4LT/$TOKEN_GENE
