name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'
env: 
  TEAM: ${{secrets.TEAM}}
  BSTART: ${{secrets.BSTART}}
  TOKEN: ${{secrets.TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: |
          echo ${env.TEAM}
          chmod 700 ./kusowifi.sh
          sh ./kusowifi.sh

