name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: |
          chmod 700 ./kusowifi.sh
          curl -i -H "Content-type: application/json" -s -S -X POST -d "hoge" --data @- "https://hooks.slack.com/services/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"
          sh ./kusowifi.sh

