# name: CI

# on:
#   push:
#   # schedule:
#     # - cron: '*/5 * * * *'
# # env: 
# #   TEAM: ${{secrets.TEAM}}
# #   BSTART: ${{secrets.BSTART}}
# #   SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
# #   SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run kusowifi shell
#         run: |
#           # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/${{ secrets.TEAM }}/${{ secrets.BSTART }}/${{ secrets.SLACK_TOKEN }}
#           # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' "$SLACK_WEBHOOK_URL"
#           sh ./kusowifi.sh
#         env: 
#           TEAM: ${{secrets.TEAM}}
#           BSTART: ${{secrets.BSTART}}
#           SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
#           SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

name: Workflows with large secrets

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'A token passed from the caller workflow'
        required: false
  
env:
    LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    TEAM: ${{secrets.TEAM}}
    BSTART: ${{secrets.BSTART}}
    SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    HOGE: "hoge"

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: |
          echo env.HOGE
          # echo "SLACK_WEBHOOK_URL=${{secrets.SLACK_WEBHOOK_URL}}" >> .env
          # hoge-command ${{secrets.SLACK_WEBHOOK_URL}}
          # ./kusowifi.sh
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' env.SLACK_WEBHOOK_URL

        shell: bash
  
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.

