name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: sh ./kusowifi.sh

