name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: sh ./kusowifi.sh
        env: 
          SLACK_WEB_HOOK: ${{secrets.SLACK_WEB_HOOK}}
