# name: CI

# on:
#   push:
#   # schedule:
#     # - cron: '*/5 * * * *'
# # env: 
# #   TEAM: ${{secrets.TEAM}}
# #   BSTART: ${{secrets.BSTART}}
# #   SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
# #   SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run kusowifi shell
#         run: |
#           # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/${{ secrets.TEAM }}/${{ secrets.BSTART }}/${{ secrets.SLACK_TOKEN }}
#           # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' "$SLACK_WEBHOOK_URL"
#           sh ./kusowifi.sh
#         env: 
#           TEAM: ${{secrets.TEAM}}
#           BSTART: ${{secrets.BSTART}}
#           SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
#           SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

name: Test work

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          # echo $HOGE これが正解っぽい
          # ./kusowifi.sh
          curl -X POST -H "Content-type: application/json" --data '{"text":"Hello, World!"}' '$SLACK_WEBHOOK_URL'
