name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'
# env: 
#   TEAM: ${{secrets.TEAM}}
#   BSTART: ${{secrets.BSTART}}
#   SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
#   SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: |
          sh ./kusowifi.sh
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          TEAM: ${{secrets.TEAM}}
          BSTART: ${{secrets.BSTART}}
          TOKEN: ${{secrets.SLACK_TOKEN}}
          TOKEN_GENE: “nUF9Jp7JrWK30VvL0z6SggPy”
