name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'
env: 
  TEAM: ${{secrets.TEAM}}
  BSTART: ${{secrets.BSTART}}
  SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: |
          # chmod 700 ./kusowifi.sh
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/$TEAM/$BSTART/$SLACK_TOKEN


