name: CI

on:
  push:
  # schedule:
    # - cron: '*/5 * * * *'
env: 
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  KUSO: ${{secrets.KUSO}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run kusowifi shell
        run: |
          chmod 700 ./kusowifi.sh
          echo ${env.KUSO}
          curl -X POST -H 'Content-type: application/json' --data "$(slackData)" ${env.KUSO}
